---
-   import_tasks: docker_install.yml

-   name: Create network
    docker_network:
        name: monitor
        state: present

-   name: Setup node exporter
    docker_container:
        name: node_exporter
        image: prom/node-exporter:v1.2.2
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        ports:
            - "9100:9100"
        restart_policy: "unless-stopped"

- name: Create the nginx-prometheus-exporter container
  community.docker.docker_container:
    name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.4.2
    command: [
      '--nginx.scrape-uri=https://{{ domain_name }}/metrics',
      '--nginx.retries=10',
      '--nginx.ssl-verify=false',
      '--web.telemetry-path=/prometheus',
    ]
    ports:
      - "9113:9113"
    state: started

#-   name: install Node Exporter
#    get_url:
#        url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
#        dest: /home/node_exporter-0.18.1.linux-amd64.tar.gz

#-   name: Extract archive
#    unarchive:
#        src: /home/node_exporter-0.18.1.linux-amd64.tar.gz
#        dest: /home/node_exporter-0.18.1.linux-amd64
#        remote_src: yes

# -   name: Create a user
#     user:
#         name: node_exporter
#         shell: /bin/false
#         state: present

# -   name: Copy node_exporter file
#     copy:
#         src: /home/node_exporter-0.18.1.linux-amd64/node_exporter
#         dest: /usr/local/bin
#         remote_src: yes

# -   name: Run chown for exporter file
#     file:
#         path: /usr/local/bin/node_exporter
#         owner: node_exporter
#         group: node_exporter

# -   name: Remove service file
#     file:
#         path: /etc/systemd/system/node_exporter.service
#         state: absent
#
# -   name: Create service file
#     file:
#         path: /etc/systemd/system/node_exporter.service
#         state: touch
#         mode: "0600"
#
# -   name: Node exporter config
#     blockinfile:
#         path: /etc/systemd/system/node_exporter.service
#         block: |
#             [Unit]
#             Description=Node Exporter
#             After=network-online.target
#
#             [Service]
#             User=node_exporter
#             Group=node_exporter
#             Type=simple
#             ExecStart=/usr/local/bin/node_exporter
#
#             [Install]
#             WantedBy=multi-user.target

# -   name: Reload daemon
#     command: |
#         sudo systemctl daemon-reload
#
# -   name: Start node Exporter
#     command: |
#         sudo systemctl start node_exporter

# -   name: Enable the node exporter service
#     command: |
#         sudo systemctl enable node_exporter

# -   name: Install Prometheus
#     get_url:
#         url: https://github.com/prometheus/prometheus/releases/download/v2.10.0/prometheus-2.10.0.linux-amd64.tar.gz
#         dest: /home/deploy/prometheus-2.10.0.linux-amd64.tar.gz
#
# -   name: Extract archive
#     unarchive:
#         src: /home/prometheus-2.10.0.linux-amd64.tar.gz
#         dest: /home/deploy
#         remote_src: yes

#-   name: Edit prometheus config file
#    template:
#        src: files/prometheus.yml
#        dest: /home/deploy/prometheus-2.10.0.linux-amd64/prometheus.yml

#-   name: Kill prometheus service
#    command: sudo pkill prometheus

#-   name: Start prometheus service
#    shell: nohup ./prometheus > prometheus.log 2>&1 &
#    args:
#        chdir: prometheus-2.10.0.linux-amd64

# -   name: Download Grafana
#     get_url:
#         url: https://dl.grafana.com/oss/release/grafana_6.2.4_amd64.deb
#         dest: /home/grafana_6.2.4_amd64.deb

# -   name: Extract deb archive and start service
#     command: sudo dpkg -i grafana_6.2.4_amd64.deb

# -   name: Add a Prometheus user
#     command: sudo useradd -rs /bin/false prometheus

# -   name: Install mysql_exporter
#     get_url:
#         url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.11.0/mysqld_exporter-0.11.0.linux-amd64.tar.gz
#         dest: /home/deploy/mysqld_exporter-0.11.0.linux-amd64.tar.gz

# -   name: Extract the binaries
#     command: tar xvzf mysqld_exporter-0.11.0.linux-amd64.tar.gz

# -   name: Move the binaries
#     command: sudo mv mysqld_exporter-0.11.0.linux-amd64/mysqld_exporter /usr/local/bin/
