---

-   name: Update apt-cache and upgrade
    apt:
        force_apt_get: yes
        update_cache: "True"
        cache_valid_time: 3600
        upgrade: yes

-   name: Install prerequisites
    apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common', python-pip]

-   name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

-   name: Add Docker APT repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

-   name: Install Docker
    apt:
        name: docker-ce

-   name: Install Docker Module for Python
    pip:
        name: docker

    name: Start microblog container
    docker_container:
        name: microblog
        image: mahm17/microblog:latest
        env:
            SECRET_KEY: "my-secret-key"
            DATABASE_URL: mysql+pymysql://microblog:zxcqweasd123@{{ groups.database[0] }}:3306/microblog_db
        ports:
            - "8000:5000"
        exposed_ports:
            - "8000"
        network_mode: host
        pull: yes

-   name: Pull the statsd container
    command: docker pull prom/statsd-exporter

-   name: Template the statsd conf file
    template:
        src: files/statsd.conf2
        dest: statsd.conf

-   name: Start the statsd container
    command: docker run -dP --net=host -v ${PWD}/statsd.conf:/statsd/statsd.conf prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"
