---

-   name: Update apt-cache and upgrade
    apt:
        force_apt_get: yes
        update_cache: "True"
        cache_valid_time: 3600
        upgrade: yes

    # Install prerequisites
#-   name: Install packages
#    ansible.builtin.pip:
#        name: "{{ packages }}"
#        state: latest

#-   name: Install docker
#    command: pip3 install docker

#-   name: Add Docker GPG key
#    become: true
#    apt_key: 
#        url: https://download.docker.com/linux/ubuntu/gpg
#        state: present

#-   name: Add Docker APT repository
#    become: true
#    apt_repository:
#        repo: deb https://download.docker.com/linux/debian buster stable
#        state: present

    # Install Docker
#-   apt:
#        name: docker-ce

    # Install Docker Module for Python
#-   name: Install docker   
#    ansible.builtin.pip:
#        name: docker
- name: Pull the latest image from dockerhub
  command: docker pull mahm17/microblog:flask-exporter

-   name: Start microblog container
    docker_container:
        name: microblog
        image: mahm17/microblog:flask-exporter
        env:
            SECRET_KEY: "my-secret-key"
            DATABASE_URL: mysql+pymysql://microblog:database@{{ groups['database'][0] }}:3306/microblog_db
        ports:
            - "8000:5000"
        #exposed_ports:
        #    - "8000"
        pull: yes

#-   name: Pull the statsd container
#    command: docker pull prom/statsd-exporter

#-   name: Template the statsd conf file
#    template:
#        src: files/statsd.conf2
#        dest: statsd.conf

#-   name: Start the statsd container
#    command: docker run -dP --net=host -v ${PWD}/statsd.conf:/statsd/statsd.conf prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"
