apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
      - image: mahm17/microblog:flask-exporter
        imagePullPolicy: Always
        name: microblog
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE
            value: mysql
          - name: DATABASE_URL
            value: mysql+pymysql://microblog:micropassw@mysql/microblog_db
        livenessProbe:
          httpGet:
            path: /
            port: 5000