global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs: 
      - targets: ["0.0.0.0:9090"]
  - job_name: "flask_local"
    static_configs:
      - targets: ["prod:5000"]
        labels:
          instance: flask_local
