---
-   name: Copy grafana config
    template:
        src: files/grafana.ini
        dest: /home/deploy/grafana.ini

-   name: Copy flask dashboard config
    copy:
        src: files/flask_dashboard.json
        dest:  /home/deploy/flask_dashboard.json

-   name: Create grafana volume
    docker_volume:
        name: grafana-data

-   name: Create grafana directory
    file:
        path: /etc/grafana
        state: directory
        mode: '777'

#-   name: Move grafana file
#    command: mv /tmp/grafana.ini /etc/grafana/grafana.ini

-   name: Setup grafana container
    docker_container:
        name: grafana
        image: grafana/grafana:8.2.4
        volumes:
            - /home/deploy/grafana.ini:/etc/grafana/grafana.ini
            - grafana-data:/var/lib/grafana
        restart_policy: "unless-stopped"
        ports:
            - "3000:3000"
#- name: Copy Nginx exporter file to host
#  copy:
#    src: files/nginx_exporter.json
#    dest: /home/deploy/nginx_exporter.json
          
-   name: Setup prometheus datasource
    community.grafana.grafana_datasource:
        name: prometheus
        ds_type: prometheus
        ds_url: "http://{{ groups.monitoring[0] }}:9090"
        url: "http://0.0.0.0:3000"
        grafana_user: "admin"
        grafana_password: "admin"

-   name: Set up the "node-exporter full" dashboard
    community.grafana.grafana_dashboard:
        grafana_url: "http://0.0.0.0:3000"
        grafana_user: "admin"
        grafana_password: "admin"
        dashboard_id: 1860
        dashboard_revision: 22
        overwrite: true

-   name: Set up the "flask app" dashboard
    community.grafana.grafana_dashboard:
        grafana_url: "http://0.0.0.0:3000"
        grafana_user: "admin"
        grafana_password: "admin"
        path: "/home/deploy/flask_dashboard.json"
        overwrite: true
        #path: "https://gist.githubusercontent.com/AndreasArne/433f902f9b986c301f2b2877454a581f/raw/4898bb2013b469cf74ace82d2d5aa39e073cb069/flaskdash.json"

-   name: Set up the "nginx" dashboard
    community.grafana.grafana_dashboard:
        grafana_url: "http://0.0.0.0:3000"
        grafana_user: "admin"
        grafana_password: "admin"
        #path: "/home/deploy/nginx_exporter.json"
        overwrite: true
        dashboard_id: 12708