---
sg_groups:
    -   name: loadBalancer
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTPS
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: appServer
        port_rules:
        -   name: APP
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 8000
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: database
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: MYSQL
            protocol: Tcp
            destination_port_range: 3306
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: monitoring
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: prometheus
            protocol: Tcp
            destination_port_range: 9090
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: alert
            protocol: Tcp
            destination_port_range: 9093
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: grafana
            protocol: Tcp
            destination_port_range: 3000
            access: Allow
            priority: 1004
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'

#---
#    sg_groups:
#        - name: load-balancer
#          description: SG for the load balancer
#          port_rules:
#          - proto: tcp
#            from_port: 22
#            to_port: 22
#            cidr_ip: 0.0.0.0/0
#          - proto: tcp
#            from_port: 80
#            to_port: 80
#            cidr_ip: 0.0.0.0/0
#          - proto: tcp
#            from_port: 443
#            to_port: 443
#            cidr_ip: 0.0.0.0/0
#          - proto: tcp
#            from_port: 9113
#            to_port: 9113
#            cidr_ip: {{ groups['monitoring'][0] }}/32
#        - name: app-server
#          description: SG for the application server
#          port_rules:
#          - proto: tcp
#            from_port: 22
#            to_port: 22
#            cidr_ip: 0.0.0.0/0
#          - proto: tcp
#            from_port: 8000
#            to_port: 8000
#            cidr_ip: {{ groups['loadBalancer'][0] }}/32
#          - proto: tcp
#            from_port: 9102
#            to_port: 9102
#            cidr_ip: {{ groups['monitoring'][0] }}/32
#        - name: database
#          description: SG for the database node
#          port_rules:
#          - proto: tcp
#            from_port: 22
#            to_port: 22
#            cidr_ip: 0.0.0.0/0
#          - proto: tcp
#            from_port: 3306
#            to_port: 3306
#            cidr_ip: {{ groups['appServer'][0] }}/32
#          - proto: tcp
#            from_port: 9104
#            to_port: 9104
#            cidr_ip: {{ groups['monitoring'][0] }}/32
#        - name: monitoring
#          description: SG for the monitoring node
#          port_rules:
#          - proto: tcp
#            from_port: 22
#            to_port: 22
#            cidr_ip: 0.0.0.0/0
          # - proto: tcp
          #   from_port: 9090
          #   to_port: 9090
          #   cidr_ip: 0.0.0.0/0
          # - proto: tcp
          #   from_port: 9093
          #   to_port: 9093
          #   cidr_ip: 0.0.0.0/0
#          - proto: tcp
#            from_port: 3000
#            to_port: 3000
#            cidr_ip: 0.0.0.0/0
          # - proto: tcp
          #   from_port: 9100
          #   to_port: 9100
          #   cidr_ip: 0.0.0.0/0
          # - proto: tcp
          #   from_port: 9104
          #   to_port: 9104
          #   cidr_ip: {{ groups['database'][0] }}/32
          # - proto: tcp
          #   from_port: 9093
          #   to_port: 9093
          #   cidr_ip: 0.0.0.0/0
          # - proto: tcp
          #   from_port: 9125
          #   to_port: 9125
          #   cidr_ip: {{ groups['appServer'][0] }}/32
          # - proto: tcp
          #   from_port: 9113
          #   to_port: 9113
          #   cidr_ip: {{ groups['loadBalancer'][0] }}/32
