---
-   name: Setup prometheus by templating config file
    template:
        src: templates/prometheus.yml
        dest: /home/deploy/prometheus.yml

-   name: Create volume for prometheus
    docker_volume:
        name: prometheus-data

-   name: Create prometheus directory if it does not exist
    file:
        path: /etc/prometheus
        state: directory
        mode: '777'

#-   name: Move prometheus.yml file
#    command: mv /home/deploy/prometheus.yml /etc/prometheus/prometheus.yml

-   name: Setup prometheus container
    docker_container:
        name: prometheus
        image: prom/prometheus:v2.31.1
        volumes:
            - /home/deploy/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--storage.tsdb.retention.time=24h"
            - "--web.enable-lifecycle"
        #ports:
        #    - "9090:9090"
        restart_policy: "unless-stopped"
        network_mode: host
        recreate: yes