# Provision servers on AWS
---
    -   hosts: local
        connection: local # Keep ansible from open ssh connection
        gather_facts: False
        #no_log: True
        collections:
            - azure.azcollection
        roles:
            -   security_groups
